### ISSUE TITLE
macos install shell

### ISSUE THREAD

**Issue by DonkeyHang** [ZaVang/GPT-SoVits#2]
hi，实在是对WebUI的操作方式提不起兴趣，特别麻烦且不直观，看到了这个cmd line的方式
请教一个环境配置的问题，

我本地用的是macos，我看install.sh中的安装方式是linux对吗，
`conda install pytorch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 pytorch-cuda=11.8 -c pytorch -c nvidia`
mbp是没有nvidia和cuda的，我也不是arm芯片，
我按照官方的方式去配macos环境对应你的repo可以跑吗，我本地有xcode，默认配置的是clang，已经配置好了ffmpeg和cmake日常要用，

又或者可以怎样修改install.sh文件呢？

谢谢

**Comment by ZaVang** [comment]
mac上也可以安装anaconda的，网上搜一搜教程很多。然后你可以根据pytorch官网选择需要的安装方式：https://pytorch.org/

**Comment by DonkeyHang** [comment]
嗯嗯 这个我知道 我是看到了nvidia相关的指令 mac没这玩意儿 我按照原分支配置方式去做了
