### ISSUE TITLE
关于使用命令行完成数据集的音频切分的方式的相关问题

### ISSUE THREAD

**Issue by himmeled** [ZaVang/GPT-SoVits#3]
大佬你好，我想问一下，官方在指出使用命令行完成数据集的音频切分的方式中，命令python audio_slicer.py \
    --input_path "<path_to_original_audio_file_or_directory>" ........  这个audio_slicer.py是在哪里的呢，只看到tools下面有一个slice_audio.py是这个文件吗？但是我使用slice_audio.py会报错。感谢大佬

**Comment by ZaVang** [comment]
因为我自己没有这一部分的需要，所以我没动原项目里处理音频的部分。我看了一下也没找到文档里说的文件，看起来应该就是slice_audio.py这个文件，但是他的参数和文档里写的不一样，所以直接跑还是会出错的。需要的话我后面找个时间修一下。

**Comment by ZaVang** [comment]
fixed by 73ea572285283522d9b3e6538aaf5ef6e8261a5c

**Comment by himmeled** [comment]
> fixed by [73ea572](https://github.com/ZaVang/GPT-SoVits/commit/73ea572285283522d9b3e6538aaf5ef6e8261a5c)

感谢大佬
