### ISSUE TITLE
推理中断的问题

### ISSUE THREAD

**Issue by himmeled** [ZaVang/GPT-SoVits#5]
大佬你好，我今天在做推理的时候，发生了中断问题，昨天推理倒是没出现这个问题，能麻烦您看看吗。有可能是机器的原因吗，我换了一台机器。
![image](https://github.com/ZaVang/GPT-SoVits/assets/50981141/18f8f1e9-4875-4110-8e89-13ee59fcc26d)

**Comment by ZaVang** [comment]
光看这个信息我倒看不出来发生了什么。。。你有试过重新跑一遍吗，是偶发性的还是必现吗

**Comment by himmeled** [comment]
> 光看这个信息我倒看不出来发生了什么。。。你有试过重新跑一遍吗，是偶发性的还是必现吗

必现：(。我跑了好多次，我现在尝试换机器看能不能解决

**Comment by himmeled** [comment]
![image](https://github.com/ZaVang/GPT-SoVits/assets/50981141/52bcfbbe-717b-484e-a875-461a6b05e4d4)
现在是这样的，还是必然出现推理中断，前面几个步骤都没有问题

**Comment by ZaVang** [comment]
你有听过实际的产生的音频吗，正常跑的时候它显示的就是这样的

**Comment by ZaVang** [comment]
> ![image](https://private-user-images.githubusercontent.com/50981141/325952509-52bcfbbe-717b-484e-a875-461a6b05e4d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzA2MDksIm5iZiI6MTcxNDEzMDMwOSwicGF0aCI6Ii81MDk4MTE0MS8zMjU5NTI1MDktNTJiY2ZiYmUtNzE3Yi00ODRlLWE4NzUtNDYxYTZiMDVlNGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YmYyYjJmMTg4MDMyZDE0Mzk0MDE3MzNkOWE2NWNhOWU5NTQ1NDY3NTI1NjJjMTk2ZTM4NjFjNjFkNWYzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AvJU731NEDmIfOOVubXGNJviIwf4A6DVnHXSg0xFp7M) 现在是这样的，还是必然出现推理中断，前面几个步骤都没有问题

这不是保存了吗，你听一下实际保存的音频有问题吗，正常跑的时候显示的就是这样的。

**Comment by himmeled** [comment]
> > ![image](https://private-user-images.githubusercontent.com/50981141/325952509-52bcfbbe-717b-484e-a875-461a6b05e4d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzA2MDksIm5iZiI6MTcxNDEzMDMwOSwicGF0aCI6Ii81MDk4MTE0MS8zMjU5NTI1MDktNTJiY2ZiYmUtNzE3Yi00ODRlLWE4NzUtNDYxYTZiMDVlNGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YmYyYjJmMTg4MDMyZDE0Mzk0MDE3MzNkOWE2NWNhOWU5NTQ1NDY3NTI1NjJjMTk2ZTM4NjFjNjFkNWYzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AvJU731NEDmIfOOVubXGNJviIwf4A6DVnHXSg0xFp7M) 现在是这样的，还是必然出现推理中断，前面几个步骤都没有问题
> 
> 这不是保存了吗，你听一下实际保存的音频有问题吗，正常跑的时候显示的就是这样的。

不好意思，忘记回复。这台机器跑出来的音频是正常的，之前中断那台机器跑出来音频是参考音频，确实是中断的。
