### ISSUE TITLE
onnx export error

### ISSUE THREAD

**Issue by DonkeyHang** [ZaVang/GPT-SoVits#6]
hi，您好，
我想问个问题，您导出过onnx文件碰到过这个问题吗，目前infer整个过程使用训练出来的模型都是ok的，所以模型大概率没有啥问题，我想使用onnx_export.py去导出onnx文件，然后失败了，单步发现卡在core_vq.py，
```
/Users/donkeyddddd/Documents/Rx_projects/git_projects/GPT_Sovits_cmdline/src/module/core_vq.py:142: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.inited:
```
这里觉得有点奇怪，按理来说core_vq里面的init只是初始化了一个bool值而已

导出路径修改如下：
```
gpt_path = "GPT_weights/my_gpt_model.ckpt"
vits_path = "SoVITS_weights/my_vits_model.pth"
exp_path = "my_model"
export(vits_path, gpt_path, exp_path)
```

然后export函数去run起来，再跳转到T2SModel.export()中line148的torch.onnx.export(...)时候报错，暂时有点懵，搜了一些内容也不太懂为什么，希望可以讨论下

谢谢

**Comment by ZaVang** [comment]
我自己没这块需求，所以之前没用过这块代码，也没改。如果需要的话我可能得稍微修改一下里面的一些地方。直接跑应该跑不起来

**Comment by ZaVang** [comment]
pytorch升级成2.1以上试试看，我这边的报错是`torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unflatten' to ONNX opset version 16 is not supported. `
查了下pytorch的文档，2.1.0以上才支持这个算子。我这边升级之后导出是没问题的

**Comment by DonkeyHang** [comment]
> pytorch升级成2.1以上试试看，我这边的报错是`torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unflatten' to ONNX opset version 16 is not supported. ` 查了下pytorch的文档，2.1.0以上才支持这个算子。我这边升级之后导出是没问题的

好的，我再试一试

**Comment by DonkeyHang** [comment]
更新后导出成功了，目前版本是这样的
```
onnx                      1.16.0
onnxruntime               1.16.3
```

另外，请问up有试过svc相关的内容么，除了tts相关的

**Comment by ZaVang** [comment]
> 更新后导出成功了，目前版本是这样的
> 
> ```
> onnx                      1.16.0
> onnxruntime               1.16.3
> ```
> 
> 另外，请问up有试过svc相关的内容么，除了tts相关的

so-vits-svc吗，大概一年前试过，但是那个后面加了太多其他功能，更新之后我就没怎么用了。

**Comment by DonkeyHang** [comment]
> > 更新后导出成功了，目前版本是这样的
> > ```
> > onnx                      1.16.0
> > onnxruntime               1.16.3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外，请问up有试过svc相关的内容么，除了tts相关的
> 
> so-vits-svc吗，大概一年前试过，但是那个后面加了太多其他功能，更新之后我就没怎么用了。

感觉up你有很多见解，方便微信吗

**Comment by ZaVang** [comment]
> > > 更新后导出成功了，目前版本是这样的
> > > ```
> > > onnx                      1.16.0
> > > onnxruntime               1.16.3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 另外，请问up有试过svc相关的内容么，除了tts相关的
> > 
> > 
> > so-vits-svc吗，大概一年前试过，但是那个后面加了太多其他功能，更新之后我就没怎么用了。
> 
> 感觉up你有很多见解，方便微信吗

自己业余爱好，整着玩的。不过可以一起讨论一下，我加你吧

**Comment by DonkeyHang** [comment]
> > > > 更新后导出成功了，目前版本是这样的
> > > > ```
> > > > onnx                      1.16.0
> > > > onnxruntime               1.16.3
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 另外，请问up有试过svc相关的内容么，除了tts相关的
> > > 
> > > 
> > > so-vits-svc吗，大概一年前试过，但是那个后面加了太多其他功能，更新之后我就没怎么用了。
> > 
> > 
> > 感觉up你有很多见解，方便微信吗
> 
> 自己业余爱好，整着玩的。不过可以一起讨论一下，我加你吧

哈哈哈哈，一样，我也是业余兴趣爱好，我微信号是donkeyddddd，握爪

**Comment by ZaVang** [comment]
> > > > > 更新后导出成功了，目前版本是这样的
> > > > > ```
> > > > > onnx                      1.16.0
> > > > > onnxruntime               1.16.3
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 另外，请问up有试过svc相关的内容么，除了tts相关的
> > > > 
> > > > 
> > > > so-vits-svc吗，大概一年前试过，但是那个后面加了太多其他功能，更新之后我就没怎么用了。
> > > 
> > > 
> > > 感觉up你有很多见解，方便微信吗
> > 
> > 
> > 自己业余爱好，整着玩的。不过可以一起讨论一下，我加你吧
> 
> 哈哈哈哈，一样，我也是业余兴趣爱好，我微信号是donkeyddddd，握爪

ok，我先close了
